services:
  ukidukirpg:
    image: ukidukirpg
    build:
      context: .
      dockerfile: UkiDukiRPG/Dockerfile

  ukidukirpg.api:
    image: ukidukirpg.api
    build:
      context: .
      dockerfile: UkiDukiRPG.API/Dockerfile

